[package]
name = "doodle-web"
version = "0.1.0"
edition = "2021"
authors = ["Théo Plénet <theo.plenet@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
